//
//  ReviewPresenter.swift
//  HittaTechAssignment
//
//  Created by Raluca Toadere on 08/12/2018.
//  Copyright (c) 2018 Raluca Toadere. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewPresentationLogic {
}

class ReviewPresenter: ReviewPresentationLogic {
    weak var viewController: ReviewDisplayLogic?
}
