//
//  ReviewRouter.swift
//  HittaTechAssignment
//
//  Created by Raluca Toadere on 08/12/2018.
//  Copyright (c) 2018 Raluca Toadere. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewRoutingLogic: class {
    func routeToCompanyPage()
}

protocol ReviewDataPassing {
    var dataStore: ReviewDataStore? { get }
}

class ReviewRouter: NSObject, ReviewRoutingLogic, ReviewDataPassing {
    weak var viewController: ReviewViewController?
    var dataStore: ReviewDataStore?

    func routeToCompanyPage() {
        viewController!.dismiss(animated: true, completion: nil)
    }
}
